/**:
  ros__parameters:
    # 开机直接到「平放向前」，与 joystick HOME_POSITION 一致
    type: "servo"
    action:
      action_name: "init"
    servo:
      id1: 500
      id2: 750
      id3: 0
      id4: 375
      id5: 500
      id10: 500
      duration: 1
